import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,Plus,Search,Settings,Terminal,Wifi,Power,Lightbulb,Monitor,Speaker,Gamepad2,Plug,Shield,SlidersHorizontal,Sparkles,Trash2,Watch,Headphones,Camera,Thermometer,RefreshCw} from 'lucide-react';
import {INTEGRATIONS,DEVICE_TYPES,getIntegration} from './integrations';
import './styles.css';

const TYPES={Light:Lightbulb,TV:Monitor,Audio:Speaker,Console:Gamepad2,Plug,Sensor:Thermometer,Camera,Watch,Headphones,Other:SlidersHorizontal};
const nav=[['Inicio',Home],['Dispositivos',SlidersHorizontal],['Escenas',Sparkles]];

function App(){
 const [page,setPage]=useState('Inicio');
 const [devices,setDevices]=useState(()=>JSON.parse(localStorage.getItem('nexus-devices')||'null')||[]);
 const [dark,setDark]=useState(()=>localStorage.getItem('nexus-theme')!=='light');
 const [query,setQuery]=useState(''); const [toast,setToast]=useState(''); const [showAdd,setShowAdd]=useState(false); const [terminal,setTerminal]=useState(false);
 useEffect(()=>localStorage.setItem('nexus-devices',JSON.stringify(devices)),[devices]);
 useEffect(()=>localStorage.setItem('nexus-theme',dark?'dark':'light'),[dark]);
 useEffect(()=>{const f=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('.search input')?.focus()}if(e.key==='Escape'){setTerminal(false);setShowAdd(false)}};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[]);
 const notify=x=>{setToast(x);setTimeout(()=>setToast(''),2200)};
 const filtered=useMemo(()=>devices.filter(d=>(d.name+' '+d.type+' '+d.room+' '+d.integration).toLowerCase().includes(query.toLowerCase())),[devices,query]);
 const addDevice=d=>{setDevices(x=>[...x,{...d,id:crypto.randomUUID(),connected:false}]);setShowAdd(false);notify('Dispositivo agregado · listo para conectar')};
 const toggle=id=>{setDevices(x=>x.map(d=>d.id===id?{...d,connected:!d.connected}:d));notify('Estado local actualizado · la conexión física depende de la integración')};
 const remove=id=>{setDevices(x=>x.filter(d=>d.id!==id));notify('Dispositivo eliminado')};
 return <div className={dark?'app':'app light'}><div className="aurora a1"/><div className="aurora a2"/>
 <aside className="sidebar"><div className="brand"><div className="brandMark">N</div><div><b>NEXUS</b><span>DEVICE CONTROL</span></div></div><nav>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideBottom"><button onClick={()=>setTerminal(true)}><Terminal size={18}/><span>Terminal</span></button><button onClick={()=>setPage('Ajustes')}><Settings size={18}/><span>Ajustes</span></button></div></aside>
 <main><header><div className="mobileBrand"><div className="brandMark">N</div><b>NEXUS</b></div><div className="search"><Search size={17}/><input placeholder="Buscar dispositivos..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><div className="headActions"><button className="iconBtn" onClick={()=>setTerminal(true)}><Terminal size={18}/></button><button className="avatar" onClick={()=>setDark(!dark)}>N</button></div></header>
 <section className="content"><div className="eyebrow"><span className="pulse"/> NEXUS LOCAL <span>•</span> {devices.length} DISPOSITIVOS</div>
 <div className="hero"><div><h1>{page==='Inicio'?'Tu casa, conectada.':page}</h1><p>Agrega dispositivos inteligentes de distintas marcas y elige cómo conectarlos. NEXUS usa una arquitectura extensible para añadir nuevas integraciones sin rehacer la app.</p><div className="heroBtns"><button className="primary" onClick={()=>setShowAdd(true)}><Plus size={17}/> Agregar dispositivo</button><button className="secondary" onClick={()=>setPage('Dispositivos')}><SlidersHorizontal size={17}/> Gestionar</button></div></div><div className="orb"><div className="orbCore"><Wifi size={28}/></div></div></div>
 {page==='Inicio'&&<Dashboard devices={filtered} toggle={toggle} remove={remove} add={()=>setShowAdd(true)}/>} {page==='Dispositivos'&&<DeviceList devices={filtered} toggle={toggle} remove={remove} add={()=>setShowAdd(true)}/>} {page==='Escenas'&&<Scenes notify={notify}/>} {page==='Ajustes'&&<SettingsPage dark={dark} setDark={setDark} clear={()=>{setDevices([]);notify('Dispositivos limpiados')}}/>}
 <footer><span>NEXUS v2.3 • Extensible Device Control</span><span><Shield size={13}/> Integraciones modulares</span></footer></section></main>
 {toast&&<div className="toast"><span>✓</span>{toast}</div>} {showAdd&&<AddModal onClose={()=>setShowAdd(false)} onAdd={addDevice}/>} 
 {terminal&&<div className="modal" onClick={()=>setTerminal(false)}><div className="terminal" onClick={e=>e.stopPropagation()}><div className="termTop"><b>NEXUS TERMINAL</b><button onClick={()=>setTerminal(false)}>×</button></div><div className="termBody"><div>&gt; nexus integrations</div>{INTEGRATIONS.map(i=><div key={i.id}><span className="green">●</span> {i.name} — {i.status}</div>)}<div>&gt; ready</div><div className="cursor">█</div></div></div></div>}
 </div>
}
function Dashboard({devices,toggle,remove,add}){const online=devices.filter(d=>d.connected).length;const integrations=new Set(devices.map(d=>d.integrationId).filter(Boolean)).size;return <><div className="stats">{[['Dispositivos',devices.length,'Configurados'],['Conectados',online,'Estado local'],['Habitaciones',new Set(devices.map(d=>d.room).filter(Boolean)).size,'Configuradas'],['Integraciones',integrations,'En uso']].map(x=><div className="card stat" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small className="ok">{x[2]}</small></div>)}</div><section className="panel"><div className="panelHead"><div><span className="eyebrow">DEVICE MATRIX</span><h2>Tus dispositivos</h2></div><button className="ghost" onClick={add}><Plus size={15}/> Agregar</button></div>{devices.length?<div className="deviceGrid">{devices.slice(0,6).map(d=><Card d={d} toggle={toggle} remove={remove} key={d.id}/>)}</div>:<Empty add={add}/>}</section><IntegrationCatalog/></>}
function IntegrationCatalog(){return <section className="panel integrationPanel"><div className="panelHead"><div><span className="eyebrow">INTEGRATION HUB</span><h2>Compatibilidad</h2></div><RefreshCw size={20}/></div><div className="integrationGrid">{INTEGRATIONS.map(i=><div className="integrationCard" key={i.id}><b>{i.icon} {i.name}</b><small>{i.kind} · {i.status}</small><p>{i.description}</p></div>)}</div></section>}
function DeviceList({devices,toggle,remove,add}){return <section className="panel full"><div className="panelHead"><div><span className="eyebrow">DEVICE MATRIX</span><h2>Todos tus dispositivos</h2></div><button className="primary" onClick={add}><Plus size={15}/> Agregar</button></div>{devices.length?<div className="deviceGrid wide">{devices.map(d=><Card d={d} toggle={toggle} remove={remove} key={d.id}/>)}</div>:<Empty add={add}/>}</section>}
function Card({d,toggle,remove}){const I=TYPES[d.type]||SlidersHorizontal;const integration=getIntegration(d.integrationId);return <div className="device card"><div className="deviceTop"><div className="deviceIcon"><I size={19}/></div><span className={d.connected?'online':'offline'}><i/> {d.connected?'Conectado':'Sin conexión'}</span></div><h3>{d.name}</h3><p>{d.type} • {d.room||'Sin habitación'}</p><div className="meter"><span style={{width:d.connected?'100%':'0%'}}/></div><div className="deviceBottom"><small>{integration.name}</small><div style={{display:'flex',gap:5}}><button onClick={()=>toggle(d.id)}><Power size={12}/> {d.connected?'Desconectar':'Preparar'}</button><button onClick={()=>remove(d.id)}><Trash2 size={12}/></button></div></div></div>}
function Empty({add}){return <div className="placeholder"><Wifi size={32}/><h3>Aún no hay dispositivos</h3><p>Agrega una TV, luz, enchufe, cámara, consola, reloj, audífonos u otro dispositivo compatible.</p><button className="primary" onClick={add}><Plus size={15}/> Agregar dispositivo</button></div>}
function AddModal({onClose,onAdd}){const [name,setName]=useState('');const [type,setType]=useState('Light');const [room,setRoom]=useState('Sala');const [integrationId,setIntegrationId]=useState('matter');const integration=getIntegration(integrationId);const compatible=integration.categories.includes(type)||integrationId==='manual'||integrationId==='bridge';return <div className="modal" onClick={onClose}><div className="terminal" onClick={e=>e.stopPropagation()}><div className="termTop"><b>AGREGAR DISPOSITIVO</b><button onClick={onClose}>×</button></div><div className="termBody" style={{fontFamily:'Inter'}}><input className="formInput" placeholder="Nombre (ej. TV sala)" value={name} onChange={e=>setName(e.target.value)}/><select className="formInput" value={type} onChange={e=>setType(e.target.value)}>{DEVICE_TYPES.map(x=><option key={x}>{x}</option>)}</select><input className="formInput" placeholder="Habitación" value={room} onChange={e=>setRoom(e.target.value)}/><select className="formInput" value={integrationId} onChange={e=>setIntegrationId(e.target.value)}>{INTEGRATIONS.map(i=><option key={i.id} value={i.id}>{i.name} — {i.status}</option>)}</select><div className={compatible?'compat okBox':'compat warnBox'}>{compatible?'✓ Integración compatible con este tipo de dispositivo':'⚠️ Esta combinación requiere una integración distinta'}</div><button className="primary" disabled={!name.trim()||!compatible} onClick={()=>onAdd({name:name.trim(),type,room,integrationId})}>Guardar dispositivo</button></div></div></div>}
function Scenes({notify}){const run=name=>notify(`${name}: preparada · se ejecutará cuando sus integraciones estén conectadas`);return <section className="panel full"><div className="panelHead"><div><span className="eyebrow">SCENES</span><h2>Escenas de casa</h2></div><Sparkles size={21}/></div><p className="moduleDesc">Agrupa acciones de diferentes marcas. Las escenas usarán las integraciones disponibles de cada dispositivo.</p><div className="sceneGrid"><button className="scene card" onClick={()=>run('Modo cine')}><Monitor size={19}/><b>Modo cine</b><span>TV + audio + luces</span></button><button className="scene card" onClick={()=>run('Modo gaming')}><Gamepad2 size={19}/><b>Modo gaming</b><span>Consola + TV + luces</span></button><button className="scene card" onClick={()=>run('Apagar todo')}><Power size={19}/><b>Apagar todo</b><span>Todos los dispositivos</span></button></div></section>}
function SettingsPage({dark,setDark,clear}){return <section className="panel full"><div className="panelHead"><div><span className="eyebrow">PREFERENCES</span><h2>Ajustes</h2></div><Settings size={21}/></div><div className="settingsList"><label><span>Modo oscuro</span><input type="checkbox" checked={dark} onChange={e=>setDark(e.target.checked)}/></label><label><span>Arquitectura modular</span><b>Activa</b></label><label><span>Integraciones</span><b>{INTEGRATIONS.length} disponibles</b></label></div><button className="danger" onClick={clear}>Limpiar dispositivos guardados</button></section>}
createRoot(document.getElementById('root')).render(<App/>);
